import {
    MatAutocompleteModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCardModule,
    MatCheckboxModule,
    MatChipsModule,
    MatDatepickerModule,
    MatDialogModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatNativeDateModule,
    MatPaginatorModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatRadioModule,
    MatSelectModule,
    MatSidenavModule,
    MatSlideToggleModule,
    MatSliderModule,
    MatSnackBarModule,
    MatSortModule,
    MatStepperModule,
    MatTableModule,
    MatTabsModule,
    MatToolbarModule,
    MatTooltipModule,
    MatDividerModule,
    MatBadgeModule
} from "@angular/material";
import { OverlayModule } from '@angular/cdk/overlay';
import { CommonModule } from "@angular/common";
import { NgModule } from "@angular/core";

@NgModule({
    declarations: [],
    imports: [
        //   CommonModule,
        MatCheckboxModule,
        MatButtonModule,
        MatDialogModule,
        MatInputModule,
        MatNativeDateModule,
        //   MatAutocompleteModule,
        MatDatepickerModule,
        MatFormFieldModule,
        MatIconModule,
        MatCardModule,
        MatRadioModule,
        MatSelectModule,
        //   MatSliderModule,
        MatSlideToggleModule,
        MatMenuModule,
        MatSidenavModule,
        //   MatToolbarModule,
        //   MatListModule,
        MatGridListModule,

        MatStepperModule,
        MatTabsModule,
        MatExpansionModule,
        MatButtonToggleModule,
        MatChipsModule,
        MatProgressSpinnerModule,
        MatProgressBarModule,
        MatDialogModule,
        MatTooltipModule,
        MatSnackBarModule,
        MatTableModule,
        MatDividerModule,
        MatSortModule,
        MatPaginatorModule,
        MatBadgeModule,
        OverlayModule
    ],
    exports: [
        MatCheckboxModule,
        MatButtonModule,
        MatInputModule,
        MatDialogModule,
        MatAutocompleteModule,
        MatDatepickerModule,
        MatFormFieldModule,
        MatIconModule,
        MatRadioModule,
        MatSelectModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatNativeDateModule,
        MatMenuModule,
        MatSidenavModule,
        MatToolbarModule,
        MatListModule,
        MatGridListModule,
        MatCardModule,
        MatStepperModule,
        MatTabsModule,
        MatExpansionModule,
        MatButtonToggleModule,
        MatChipsModule,
        MatProgressSpinnerModule,
        MatProgressBarModule,
        MatDialogModule,
        MatTooltipModule,
        MatSnackBarModule,
        MatTableModule,
        MatDividerModule,
        MatSortModule,
        MatPaginatorModule,
        MatBadgeModule,
        OverlayModule
    ]
})
export class AngularMaterialModule { }
